Sql server migration for local development using Sql server inside docker container
ITU-BDSA23-GROUP10/Chirp pull request #139
Opened 2023-11-04 00:13 UTC by Slug-Boi

This implementation of SQL server with docker containers takes care of the local development side of things. This more than likely breaks the tests which will have to be fixed on a separate branch which is another issue #134 
Resolves #130

2023-11-04 09:32 UTC, August-Brandt approved these changes
It all looks good. Nice work

2023-11-04 11:00 UTC, JonasSkjodt approved these changes
looks good. The tests, as you say, can be handled in another branch.

2023-11-04 19:56 UTC, Alex-itu approved these changes

2023-11-05 18:43 UTC, Haruyzal requested changes
It seems errors occur 'cause of unremoved usings in our tests, where the .csproj doesn't recognise these anymore:
- `InMemoryWebApplicationRactory.cs` -> `Using Microsoft.Data.Sqlite`
- `ChirpRazorHttpClient_UnitTests.cs` -> `Using SimpleDB`

Banger work 🔥

2023-11-05 18:43 UTC, Haruyzal commented on src/Chirp.Web/appsettings.json
I don't think I understand why "ConnectionStrings" is empty? :)

2023-11-05 18:47 UTC, Slug-Boi commented on src/Chirp.Web/appsettings.json
Cause we are now using user-secrets forgot to say that in the PR

> It seems errors occur 'cause of unremoved usings in our tests, where the .csproj doesn't recognise these anymore:...

Most of the test need to be rewritten from the ground up to support SQL Server so think we're just going to wait with changing test stuff for another branch

2023-11-05 18:52 UTC, Slug-Boi commented on src/Chirp.Web/appsettings.json
Or are those errors happening with Dotnet run? If so just remove them and push it to the branch =)

2023-11-06 09:15 UTC, Slug-Boi commented
I have found a pretty big problem. When changing over to SQL server the Async methods used to access and change the DBContext now run into concurrency problems. Resulting in an exception being thrown when trying to access an authors timeline

2023-11-06 14:27 UTC, Haruyzal commented on src/Chirp.Web/appsettings.json
> Cause we are now using user-secrets forgot to say that in the PR
But when I run `dotnet user-secrets list --project src/Chirp.Web`, it replies: `No secrets configured for this application.` Effectively making the ConnectionStrings empty, at least on my end ^^"

2023-11-07 07:29 UTC, Slug-Boi commented on src/Chirp.Web/appsettings.json
I'll give a small presentation today on how to do it but you need to individually set the Conn string and then use docker to run the server which will allow you to get said Conn string

2023-11-07 10:28 UTC, Haruyzal approved these changes
New changes look good, awesome work guys.
- Approval sent from my iPhone.

2023-11-07 10:34 UTC, merged